url: ""

proofer:
  url_ignore:
    - "#comments"
    - !ruby/regexp '/https?:\/\/(www)?\.youtube\.com\/watch\?v=.*/i'
    - https://daveeargle.com/404/
    - /edit/master/404.html
  check_html: true

github:
  repository_nwo: "deargle/deargle.github.com"
  owner_url: "https://github.com/deargle"
  repository_url: "https://github.com/deargle/deargle.github.com"
